### PR TITLE
Add travis integration

### PR DESCRIPTION
**Pull request by SandroMachado**
Hi @thiagokimo 

This pull request adds travis integration to the repository. 
To enable the travis in this repository just follow the step 1 and 2 of the [travis integration guide](http://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A). After this PR been merged the travis should start and run the tests.

### CODE REVIEW

**Comment by thiagokimo** [comment]
Hi @SandroMachado,

It seems travis-ci build is failing. Check this out:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/69545092/log.txt

**Comment by thiagokimo** [comment]
Nevermind. It's working now :+1: 

"Obrigado"

**Comment by SandroMachado** [comment]
Ainda bem! :)

The build is failing on Android 2.3. It also happens on my fork, but after running the tests 3 times the build passed. I was reading about that and I think this could be related to this [bug](https://code.google.com/p/android/issues/detail?id=27007). What do you think?

**Comment by thiagokimo** [comment]
That is a bug from Faker which I just fixed it!

I was wrongly using the method **positiveDigit** to generate a string of digits. It generates a random value between 0 and 9, which is wrong because the string can begin with 0, forcing **Integer.parseInt** remove them.

I'll upload another version with this fix in few hours.

**Comment by SandroMachado** [comment]
Great! Thanks

**Pull request merged**
